"""initial schema

Revision ID: 5ce714c8ed57
Revises: 
Create Date: 2025-12-06 13:25:24.033661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce714c8ed57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cycles_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('self_consumption_only', sa.Boolean(), nullable=True),
    sa.Column('dynamic_pricing', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_modes_id'), 'battery_modes', ['id'], unique=False)
    op.create_index(op.f('ix_battery_modes_mode_name'), 'battery_modes', ['mode_name'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('master_data_yearly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vat_rate_batteries', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_vat_refund', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_refund_per_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_refund_per_1000wp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('energy_tax_incl_vat', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('saldering_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inflation_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('avg_dynamic_price_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', name='uq_master_data_year')
    )
    op.create_index(op.f('ix_master_data_yearly_id'), 'master_data_yearly', ['id'], unique=False)
    op.create_index(op.f('ix_master_data_yearly_year'), 'master_data_yearly', ['year'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('capacity_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_per_module_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('modules_count', sa.Integer(), nullable=True),
    sa.Column('roundtrip_efficiency', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('guaranteed_cycles', sa.Integer(), nullable=False),
    sa.Column('guaranteed_capacity_retention', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_charge_power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discharge_power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_excl_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_incl_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warranty_years', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('battery_mode_before_id', sa.Integer(), nullable=True),
    sa.Column('battery_mode_after_id', sa.Integer(), nullable=True),
    sa.Column('annual_consumption_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_generation_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_feed_in_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('solar_panel_wp', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('supply_rate_per_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('feed_in_rate_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('gas_phase_out_date', sa.Date(), nullable=True),
    sa.Column('installation_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('additional_costs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('financing_years', sa.Integer(), nullable=True),
    sa.Column('financing_interest_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('calculation_years', sa.Integer(), nullable=True),
    sa.Column('vat_scenario', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['battery_mode_after_id'], ['battery_modes.id'], ),
    sa.ForeignKeyConstraint(['battery_mode_before_id'], ['battery_modes.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_id'), 'calculations', ['id'], unique=False)
    op.create_table('calculation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('total_investment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_refund', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_investment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_savings_20_years', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_annual_savings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payback_period_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('roi_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('npv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cycles_lifetime', sa.Integer(), nullable=True),
    sa.Column('final_capacity_percentage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calculation_id')
    )
    op.create_index(op.f('ix_calculation_results_id'), 'calculation_results', ['id'], unique=False)
    op.create_table('calculation_yearly_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('cycles_this_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cumulative_cycles', sa.Integer(), nullable=True),
    sa.Column('capacity_percentage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('degradation_percentage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('consumption_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generation_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('feed_in_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grid_import_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electricity_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electricity_cost_with_battery', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_savings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cumulative_savings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('financing_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('financing_interest', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('financing_principal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_refund_this_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inflation_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_yearly_details_id'), 'calculation_yearly_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculation_yearly_details_id'), table_name='calculation_yearly_details')
    op.drop_table('calculation_yearly_details')
    op.drop_index(op.f('ix_calculation_results_id'), table_name='calculation_results')
    op.drop_table('calculation_results')
    op.drop_index(op.f('ix_calculations_id'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_master_data_yearly_year'), table_name='master_data_yearly')
    op.drop_index(op.f('ix_master_data_yearly_id'), table_name='master_data_yearly')
    op.drop_table('master_data_yearly')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_battery_modes_mode_name'), table_name='battery_modes')
    op.drop_index(op.f('ix_battery_modes_id'), table_name='battery_modes')
    op.drop_table('battery_modes')
    # ### end Alembic commands ###
